# Generated by Django 3.2 on 2023-01-04 14:09

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
            ],
        ),
        
    ]
