# Generated by Django 3.2 on 2023-01-04 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ou', '0002_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keys',
            name='platform_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ou.platform'),
        ),
    ]
