# Generated by Django 3.2 on 2023-01-04 14:34

from django.db import migrations
from ou.models import Platform

def add_default_platform(apps, schema_editor):
    Platform = apps.get_model('ou', 'Platform')
    Platform.objects.create(platform_name="First platform")

class Migration(migrations.Migration):

    dependencies = [
        ('ou', '0003_add_fields_to_keys'),
    ]



    operations = [
        migrations.RunPython(add_default_platform),
    ]
