# Generated by Django 3.2 on 2023-01-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ou', '0004_add_default_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='platform_used',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ou.platform'),
            preserve_default=False,
        ),
    ]
